#!/bin/sh
### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start aesd socket server at boot
# Description:       This script starts the aesd socket server daemon
### END INIT INFO

case "$1" in
    start)
        echo "Starting aesd socket server"
        start-stop-daemon --start --name aesdsocket -a /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "Stopping aesd socket server"
        start-stop-daemon --stop --name aesdsocket --signal TERM 
        ;;
    *)
        echo "Usage $0 {start | stop}"
        exit 1
esac

exit 0   