#! /bin/sh

case "$1" in
    start)
        echo "Starting aesd socket server"
        start-stop-daemon --start --name aesdsocket -a /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "Stopping aesd socket server"
        start-stop-daemon --stop --name aesdsocket --signal TERM 
        ;;
    *)
        echo "Usage $0 {start | stop}"
    exit 1
esac

exit 0
